services:
    - type: web
      name: formulaire-symfony-app
      env: docker
      plan: free
      autoDeploy: true
      region: frankfurt
      dockerContext: .
      dockerfilePath: ./Dockerfile
      envVars:
          - key: APP_ENV
            value: prod
          - key: APP_SECRET
            value: ton_secret_generé
